version: '3.7'

services:

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ../nginx:/etc/nginx/conf.d:ro
    networks:
      - my-proxy-net

  certbot:
    image: certbot/certbot:latest
    restart: always
    command: sh -c "sh -c "certbot certonly ${DOMAIN_ARGS} ${STAGING_ARG} ${EMAIL_ARG} --standalone --agree-tos --server https://acme-v02.api.letsencrypt.org/directory --verbose --keep-until-expiring --preferred-challenges=http & sleep 1d"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
    environment:
      DOMAIN_ARGS: ${HOST_NAME}
      STAGING_ARG: ${STAGING}
      EMAIL_ARG: ${EMAIL}

  dns:
    build: dns
    container_name: dns
    environment:
      DO_API_TOKEN: ${DO_API_TOKEN}
      DO_DOMAIN: ${DO_DOMAIN}
      DO_SUBDOMAINS: ${DO_SUBDOMAINS}
      SLEEP_INTERVAL: ${SLEEP_INTERVAL}
    command: "./run.sh"
    restart: always


volumes:
  letsencrypt:
    external:
      name: letsencrypt_keys


networks:
  my-proxy-net:
    external:
      name: ${NETWORK_NAME}
