version: '3.7'


services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot_init
    command: sh -c "certbot certonly ${DOMAIN_ARGS} ${STAGING_ARG} ${EMAIL_ARG} --standalone --agree-tos --server https://acme-v02.api.letsencrypt.org/directory --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
        - "80:80"
    depends_on:
        - dns
    environment:
      DOMAIN_ARGS: ${HOST_NAME}
      STAGING_ARG: ${STAGING}
      EMAIL_ARG: ${EMAIL}

  dns:
    build: dns
    container_name: dns_init
    environment:
      DO_API_TOKEN: ${DO_API_TOKEN}
      DO_DOMAIN: ${DO_DOMAIN}
      DO_SUBDOMAINS: ${DO_SUBDOMAINS}
      SLEEP_INTERVAL: ${SLEEP_INTERVAL}
    command: "./run.sh"


volumes:
  letsencrypt:
    name: letsencrypt_keys
