version: '3.7'

services:

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ../nginx/app.conf:/etc/nginx/app.conf:ro
    networks:
      - my-proxy-net

  certbot:
    image: certbot/certbot:latest
    restart: always
    command: sh -c "certbot certonly --standalone -d ${HOST_NAME} ${STAGING} --text --agree-tos --email ${EMAIL} --server https://acme-v02.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http && sleep 1d"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt


volumes:
  letsencrypt:
    external:
      name: letsencrypt_keys


networks:
  my-proxy-net:
    external:
      name: ${NETWORK_NAME}
