version: '3.7'


services:
  certbot:
    image: certbot/certbot:latest
    command: sh -c "certbot certonly --standalone ${DOMAINS_ARGS} ${STAGING_ARG} ${EMAIL_ARG} --text --agree-tos --server https://acme-v02.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
        - "80:80"
    depends_on:
        - dns
    environment:
      HOST_NAME: ${HOST_NAME}
      STAGING: ${STAGING}
      EMAIL: ${EMAIL}

  dns:
    build: dns
    container_name: dns
    environment:
      DO_API_TOKEN: ${DO_API_TOKEN}
      DO_DOMAIN: ${DO_DOMAIN}
      DO_SUBDOMAINS: ${DO_SUBDOMAINS}
      SLEEP_INTERVAL: ${SLEEP_INTERVAL}
    command: "./run.sh"
    restart: always


volumes:
  letsencrypt:
    name: letsencrypt_keys
